/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FlightService } from "../flight.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FlightCreateInput } from "./FlightCreateInput";
import { Flight } from "./Flight";
import { FlightFindManyArgs } from "./FlightFindManyArgs";
import { FlightWhereUniqueInput } from "./FlightWhereUniqueInput";
import { FlightUpdateInput } from "./FlightUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FlightControllerBase {
  constructor(
    protected readonly service: FlightService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Flight })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFlight(@common.Body() data: FlightCreateInput): Promise<Flight> {
    return await this.service.createFlight({
      data: data,
      select: {
        airlineName: true,
        arrivalTime: true,
        createdAt: true,
        departureTime: true,
        flightNumber: true,
        fromAirport: true,
        id: true,
        price: true,
        seatsAvailable: true,
        toAirport: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Flight] })
  @ApiNestedQuery(FlightFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async flights(@common.Req() request: Request): Promise<Flight[]> {
    const args = plainToClass(FlightFindManyArgs, request.query);
    return this.service.flights({
      ...args,
      select: {
        airlineName: true,
        arrivalTime: true,
        createdAt: true,
        departureTime: true,
        flightNumber: true,
        fromAirport: true,
        id: true,
        price: true,
        seatsAvailable: true,
        toAirport: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async flight(
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Flight | null> {
    const result = await this.service.flight({
      where: params,
      select: {
        airlineName: true,
        arrivalTime: true,
        createdAt: true,
        departureTime: true,
        flightNumber: true,
        fromAirport: true,
        id: true,
        price: true,
        seatsAvailable: true,
        toAirport: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFlight(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() data: FlightUpdateInput
  ): Promise<Flight | null> {
    try {
      return await this.service.updateFlight({
        where: params,
        data: data,
        select: {
          airlineName: true,
          arrivalTime: true,
          createdAt: true,
          departureTime: true,
          flightNumber: true,
          fromAirport: true,
          id: true,
          price: true,
          seatsAvailable: true,
          toAirport: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFlight(
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Flight | null> {
    try {
      return await this.service.deleteFlight({
        where: params,
        select: {
          airlineName: true,
          arrivalTime: true,
          createdAt: true,
          departureTime: true,
          flightNumber: true,
          fromAirport: true,
          id: true,
          price: true,
          seatsAvailable: true,
          toAirport: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        bookingDate: true,
        createdAt: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        paymentStatus: true,
        totalPrice: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async connectBookings(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async updateBookings(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "Flight",
    action: "update",
    possession: "any",
  })
  async disconnectBookings(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }
}
